[Match]
Distribution=arch

[Content]
Packages=
        amd-ucode
        apparmor
        base
        bluez
        bluez-utils
        btrfs-progs
        cups
        cups-pdf
        dmidecode
        dosfstools
        e2fsprogs
        espeakup
        flatpak
        fprintd
        fwupd
        gamemode
        glibc-locales
        hplip
        inetutils
        intel-ucode
        linux-lts
        linux-firmware
        lvm2
        man-db
        mesa
        networkmanager
        orca
        plymouth
        powertop
        power-profiles-daemon
        speech-dispatcher
        shadow
        sudo 
        tar
        thermald
        tpm2-tools
        unrar
        unzip
        usbutils
        vulkan-radeon
        vulkan-intel
        wl-clipboard
        xfsprogs
        7zip
