[Match]
Distribution=arch

[Content]
Packages=
        crane
        firewalld
        gst-plugins-good
        gst-plugin-pipewire
        noto-fonts
        noto-fonts-cjk
        noto-fonts-emoji
        noto-fonts-extra
        ttf-dejavu
        ttf-liberation
        spice-vdagent
        steam-devices

[Build]
SandboxTrees=
        repos/multilib.conf:/etc/pacman.d/multilib.conf