[Match]
Distribution=arch

[Content]
Packages=
        firewalld
        noto-fonts
        noto-fonts-cjk
        noto-fonts-emoji
        noto-fonts-extra
        ttf-dejavu
        ttf-liberation
        spice-vdagent
        steam-devices

SandboxTrees=
        repos/multilib.conf:/etc/pacman.d/multilib.conf