[Match]
Distribution=arch

[Content]
Packages=
        noto-fonts
        noto-fonts-cjk
        noto-fonts-emoji
        noto-fonts-extra
        ttf-dejavu
        ttf-liberation
        spice-vdagent
        ufw

ExtraTrees=
        subprojects/xdg-terminal-exec/xdg-terminal-exec:/usr/bin/xdg-terminal-exec