[Match]
Distribution=arch

[Content]
Packages=
        adw-gtk-theme
        evolution-data-server
        gdm
        gnome-backgrounds
        gnome-control-center
        gnome-disk-utility
        gnome-initial-setup
        gnome-keyring
        gnome-remote-desktop
        gnome-session
        gnome-shell
        gnome-user-share
        grilo-plugins
        gvfs-afc
        gvfs-dnssd
        gvfs-goa 
        gvfs-gphoto2
        gvfs-mtp
        gvfs-nfs
        gvfs-onedrive
        gvfs-smb
        gvfs-wsdd
        nautilus
        nautilus-python
        ptyxis
        rygel
        tecla
        xdg-desktop-portal-gnome

RemoveFiles=
        /usr/share/applications/avahi-discover.desktop
        /usr/share/applications/bssh.desktop
        /usr/share/applications/bvnc.desktop
        /usr/share/applications/hplip.desktop
        /usr/share/applications/hp-uiscan.desktop
        /usr/share/applications/stoken-gui.desktop
        /usr/share/applications/stoken-gui-small.desktop
        /usr/share/applications/qv4l2.desktop
        /usr/share/applications/qvidcap.desktop

ExtraTrees=
        subprojects/xdg-terminal-exec-nautilus/xdg-terminal-exec-nautilus.py:/usr/share/nautilus-python/extensions/xdg-terminal-exec-nautilus.py