[Match]
Distribution=arch

[Content]
ExtraTrees=subprojects/assets/system_files/:/
Packages=
		homebrew
		brew-proxy

[Build]
SandboxTrees=subprojects/homebrew-arch/repo.gpg:/usr/share/pacman/keyrings/lumaeris.gpg
			repos/lumaeris-trusted:/usr/share/pacman/keyrings/lumaeris-trusted
			repos/homebrew.conf:/etc/pacman.d/homebrew.conf
