[Match]
Distribution=arch

[Content]
Packages=
        android-tools
        bash-completion
        crun
        distrobox
        docker
        fastfetch
        fish
        fzf
        gcc
        git
        git-lfs
        gum
        htop
        hyfetch
        just
        make
        nano
        networkmanager-openvpn
        networkmanager-openconnect
        podman
        python-pip
        scdoc
        ttf-nerd-fonts-symbols
        vim
        wireguard-tools
        ydotool
        zenity     
        zsh
