[Match]
Profiles=bootc
Distribution=arch

[Content]
RemoveFiles=
    /usr/etc
    /var/*
    /boot/*

Packages=
    bootc
    dracut
    erofs-utils
    skopeo
    uupd

[Build]
SandboxTrees=../../subprojects/arch-bootc-pkgs/repo.gpg:/usr/share/pacman/keyrings/hecknt.gpg
             ../../repos/hecknt-trusted:/usr/share/pacman/keyrings/hecknt-trusted
             ../../repos/bootc.conf:/etc/pacman.d/bootc.conf

[Content]
# We want to use the bootc/ostree dracut modules instead of letting mkosi handle this. Please reconsider once arbitrary content can be added to the initramfs somehow
Bootable=no
KernelCommandLine=

[Output]
OciLabels=containers.bootc=1
Format=oci
