just := just_executable()

[private]
default:
    @{{ just }} --list

# Update Apollo, Flatpaks, brew packages and Distroboxes.
update:
    sudo uupd --log-level info

# Choose whether automatic updates are enabled or disabled
toggle-automatic-updates:
    #!/bin/bash
    CHOICE="$(gum choose --header="Enable automatic updates" "Enabled" "Disabled")"

    if [ "$CHOICE" = "Enabled" ]; then 
        echo "Enabling automatic updates..."
        systemctl enable --now uupd.timer
    elif [ "$CHOICE" = "Disabled" ]; then
        echo "Disabling automatic updates..."
        systemctl disable --now uupd.timer
    fi

# Toggles OpenTabletDriver configs (You will only be able to configure your art tablet in OpenTabletDriver, not in your desktop's settings)
toggle-opentabletdriver:
    #!/bin/bash
    if stat /etc/.otb-toggled &>/dev/null; then
        sudo unlink /etc/udev/rules.d/70-opentabletdriver.rules
        sudo unlink /etc/modprobe.d/99-opentabletdriver.conf
        sudo unlink /etc/modules-load.d/opentabletdriver.conf
        sudo rm /etc/.otb-toggled
        echo "Disabled OpenTabletDriver."
    else
        set -euo pipefail

        if ! flatpak info net.opentabletdriver.OpenTabletDriver &>/dev/null; then
            if gum confirm "Would you like to install OpenTabletDriver from Flathub?" ; then
                flatpak install net.opentabletdriver.OpenTabletDriver
            fi
        fi

        sudo ln -sf /usr/lib/opentabletdriver-config/udev/rules.d/70-opentabletdriver.rules /etc/udev/rules.d/70-opentabletdriver.rules
        sudo ln -sf /usr/lib/opentabletdriver-config/modprobe.d/99-opentabletdriver.conf /etc/modprobe.d/99-opentabletdriver.conf
        sudo ln -sf /usr/lib/opentabletdriver-config/modules-load.d/opentabletdriver.conf /etc/modules-load.d/opentabletdriver.conf
        sudo touch /etc/.otb-toggled
        echo "Enabled OpenTabletDriver."

        if gum confirm --default="no" "Reboot your computer to apply changes?" ; then
            reboot
        fi
    fi
