just := just_executable()

[private]
default:
    @{{ just }} --list

# Update Apollo, Flatpaks, brew packages and Distroboxes.
update:
    sudo uupd --log-level info

# Choose whether automatic updates are enabled or disabled
toggle-automatic-updates:
    #!/bin/bash
    CHOICE="$(gum choose --header="Enable automatic updates" "Enabled" "Disabled")"

    if [ "$CHOICE" = "Enabled" ]; then 
        echo "Enabling automatic updates..."
        systemctl enable --now uupd.timer
    elif [ "$CHOICE" = "Disabled" ]; then
        echo "Disabling automatic updates..."
        systemctl disable --now uupd.timer
    fi
