---
name: Build container image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/CONTRIBUTING.md"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  apollo:
    name: apollo
    uses: ./.github/workflows/build-bootc-image.yaml
    with:
      image-name: "apollo"
      image-tag: "latest"
      image-profiles: ""
    secrets: inherit
